# Generated by Django 6.0.4 on 2026-04-21 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Almacen",
            fields=[
                ("id_almacen", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("cantidad_max", models.IntegerField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
                "db_table": "almacen",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categoria",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="GesPrecio",
            fields=[
                ("id_ges_precio", models.AutoField(primary_key=True, serialize=False)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=12)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateField()),
                (
                    "metodo_inventario",
                    models.CharField(
                        choices=[
                            ("PEPS", "Primero en Entrar, Primero en Salir"),
                            ("UEPS", "Último en Entrar, Primero en Salir"),
                            ("PROMEDIO", "Promedio Ponderado"),
                        ],
                        default="PROMEDIO",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gestor de Precio",
                "verbose_name_plural": "Gestores de Precio",
                "db_table": "ges_precio",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id_marca", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "db_table": "marca",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                ("id_unidad", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("abreviatura", models.CharField(blank=True, max_length=10, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "unidad_medida",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="NotaEgreso",
            fields=[
                ("id_egreso", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("glosa", models.TextField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=200, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="egresos",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Egreso",
                "verbose_name_plural": "Notas de Egreso",
                "db_table": "nota_egreso",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="NotaIngreso",
            fields=[
                ("id_ingreso", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("glosa", models.TextField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=200, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingresos",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Ingreso",
                "verbose_name_plural": "Notas de Ingreso",
                "db_table": "nota_ingreso",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estado", models.CharField(default="activo", max_length=20)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_categoria",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="inventario.categoria",
                    ),
                ),
                (
                    "id_marca",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_marca",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="inventario.marca",
                    ),
                ),
                (
                    "id_unidad",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_unidad",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="inventario.unidadmedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "producto",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="DetalleIngreso",
            fields=[
                (
                    "id_detalle_ingreso",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "id_almacen",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_almacen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_ingreso",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "id_ingreso",
                    models.ForeignKey(
                        db_column="id_ingreso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.notaingreso",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_ingreso",
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Ingreso",
                "verbose_name_plural": "Detalles de Ingreso",
                "db_table": "detalle_ingreso",
            },
        ),
        migrations.CreateModel(
            name="DetalleEgreso",
            fields=[
                (
                    "id_detalle_egreso",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "id_almacen",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_almacen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_egreso",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "id_egreso",
                    models.ForeignKey(
                        db_column="id_egreso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.notaegreso",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_egreso",
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Egreso",
                "verbose_name_plural": "Detalles de Egreso",
                "db_table": "detalle_egreso",
            },
        ),
        migrations.CreateModel(
            name="Traspaso",
            fields=[
                ("id_traspaso", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha", models.DateField()),
                ("glosa", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
                (
                    "almacen_destino",
                    models.ForeignKey(
                        blank=True,
                        db_column="almacen_destino",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traspasos_destino",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "almacen_origen",
                    models.ForeignKey(
                        blank=True,
                        db_column="almacen_origen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traspasos_origen",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="traspasos",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traspaso",
                "verbose_name_plural": "Traspasos",
                "db_table": "traspaso",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleTraspaso",
            fields=[
                (
                    "id_detalle_traspaso",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_almacen",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_almacen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_traspaso",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_traspaso",
                        to="inventario.producto",
                    ),
                ),
                (
                    "id_traspaso",
                    models.ForeignKey(
                        db_column="id_traspaso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.traspaso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Traspaso",
                "verbose_name_plural": "Detalles de Traspaso",
                "db_table": "detalle_traspaso",
            },
        ),
        migrations.CreateModel(
            name="ProductoAlmacen",
            fields=[
                (
                    "id_producto_almacen",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stock_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stock_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "id_almacen",
                    models.ForeignKey(
                        db_column="id_almacen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        db_column="id_producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="almacenes",
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto en Almacén",
                "verbose_name_plural": "Productos en Almacén",
                "db_table": "producto_almacen",
                "unique_together": {("id_producto", "id_almacen")},
            },
        ),
    ]
