# Generated by Django 6.0.4 on 2026-04-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("paterno", models.CharField(blank=True, max_length=100, null=True)),
                ("materno", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("correo", models.EmailField(blank=True, max_length=150, null=True)),
                ("nit", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "cliente",
                "ordering": ["paterno", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="NotaVenta",
            fields=[
                ("id_venta", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_venta", models.DateField()),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("glosa", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("contado", "Contado"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                        ],
                        default="contado",
                        max_length=20,
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="ventas.cliente",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventas",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Venta",
                "verbose_name_plural": "Notas de Venta",
                "db_table": "nota_venta",
                "ordering": ["-fecha_venta"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id_detalle_venta",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_uni", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "precio_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "id_almacen",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_almacen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_venta",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_venta",
                        to="inventario.producto",
                    ),
                ),
                (
                    "id_venta",
                    models.ForeignKey(
                        db_column="id_venta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="ventas.notaventa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalles de Venta",
                "db_table": "detalle_venta",
            },
        ),
    ]
