# Generated by Django 6.0.4 on 2026-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notaventa",
            name="tipo_pago",
            field=models.CharField(
                choices=[
                    ("contado", "Contado"),
                    ("credito", "Crédito"),
                    ("transferencia", "Transferencia"),
                    ("qr", "QR"),
                ],
                default="contado",
                max_length=20,
            ),
        ),
    ]
