# Generated by Django 6.0.4 on 2026-04-27 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                ("id_diagnostico", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                ("causa_raiz", models.TextField(blank=True, null=True)),
                (
                    "tiempo_estimado_hrs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("fecha_diagnostico", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Diagnóstico",
                "verbose_name_plural": "Diagnósticos",
                "db_table": "diagnostico",
            },
        ),
        migrations.CreateModel(
            name="TipoDetalle",
            fields=[
                ("id_tipo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo de Detalle",
                "verbose_name_plural": "Tipos de Detalle",
                "db_table": "tipo_detalle",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoReparacion",
            fields=[
                (
                    "id_tipo_reparacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Tipo de Reparación",
                "verbose_name_plural": "Tipos de Reparación",
                "db_table": "tipo_reparacion",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CotizacionReparacion",
            fields=[
                ("id_cotizacion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "costo_repuesto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "mano_obra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "id_diagnostico",
                    models.OneToOneField(
                        db_column="id_diagnostico",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizacion",
                        to="reparaciones.diagnostico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización de Reparación",
                "verbose_name_plural": "Cotizaciones de Reparación",
                "db_table": "cotizacion_reparacion",
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                ("id_equipo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo_equipo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("serie_imei", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_ingreso", models.DateField(auto_now_add=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipos",
                        to="ventas.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "db_table": "equipo",
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.CreateModel(
            name="NotaReparacion",
            fields=[
                (
                    "id_nota_reparacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("falla_reportada", models.TextField()),
                ("falla_real", models.TextField(blank=True, null=True)),
                ("fecha_entrega", models.DateField(blank=True, null=True)),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("qr", "QR"),
                            ("contado", "Contado"),
                            ("transferencia", "Transferencia"),
                        ],
                        default="qr",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recibido", "Recibido"),
                            ("diagnostico", "En Diagnóstico"),
                            ("cotizado", "Cotizado"),
                            ("aprobado", "Aprobado"),
                            ("en_reparacion", "En Reparación"),
                            ("listo", "Listo"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="recibido",
                        max_length=20,
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reparaciones",
                        to="ventas.cliente",
                    ),
                ),
                (
                    "id_equipo",
                    models.ForeignKey(
                        db_column="id_equipo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reparaciones",
                        to="reparaciones.equipo",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reparaciones",
                        to="usuarios.usuario",
                    ),
                ),
                (
                    "id_tipo_reparacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tipo_reparacion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reparaciones",
                        to="reparaciones.tiporeparacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Reparación",
                "verbose_name_plural": "Notas de Reparación",
                "db_table": "nota_reparacion",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="diagnostico",
            name="id_nota_reparacion",
            field=models.OneToOneField(
                db_column="id_nota_reparacion",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostico",
                to="reparaciones.notareparacion",
            ),
        ),
        migrations.CreateModel(
            name="DetalleReparacion",
            fields=[
                (
                    "id_detalle_reparacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "precio_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "id_cotizacion",
                    models.ForeignKey(
                        db_column="id_cotizacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="reparaciones.cotizacionreparacion",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_reparacion",
                        to="inventario.producto",
                    ),
                ),
                (
                    "id_tipo_detalle",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_tipo_detalle",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles",
                        to="reparaciones.tipodetalle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Reparación",
                "verbose_name_plural": "Detalles de Reparación",
                "db_table": "detalle_reparacion",
            },
        ),
    ]
