# Generated by Django 6.0.4 on 2026-04-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
            },
        ),
        migrations.AlterModelOptions(
            name="productoalmacen",
            options={
                "verbose_name": "Artículo en Almacén",
                "verbose_name_plural": "Artículos en Almacén",
            },
        ),
    ]
