# Generated by Django 6.0.4 on 2026-04-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                ("id_permiso", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "permiso",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PoliticaContrasena",
            fields=[
                ("id_politica", models.AutoField(primary_key=True, serialize=False)),
                ("longitud_minima", models.SmallIntegerField(default=8)),
                ("requiere_mayuscula", models.BooleanField(default=True)),
                ("requiere_numero", models.BooleanField(default=True)),
                ("requiere_especial", models.BooleanField(default=False)),
                ("max_intentos", models.SmallIntegerField(default=3)),
                ("minutos_bloqueo", models.SmallIntegerField(default=15)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Política de contraseña",
                "verbose_name_plural": "Políticas de contraseña",
                "db_table": "politica_contrasena",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "rol",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="RolPermiso",
            fields=[
                ("id_rol_permiso", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_permiso",
                    models.ForeignKey(
                        db_column="id_permiso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rol_permisos",
                        to="usuarios.permiso",
                    ),
                ),
                (
                    "id_rol",
                    models.ForeignKey(
                        db_column="id_rol",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rol_permisos",
                        to="usuarios.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol - Permiso",
                "verbose_name_plural": "Roles - Permisos",
                "db_table": "rol_permiso",
                "unique_together": {("id_rol", "id_permiso")},
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("paterno", models.CharField(blank=True, max_length=100, null=True)),
                ("materno", models.CharField(blank=True, max_length=100, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("correo", models.EmailField(max_length=150, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
                ("intentos_fallidos", models.SmallIntegerField(default=0)),
                ("bloqueado", models.BooleanField(default=False)),
                ("fecha_bloqueo", models.DateTimeField(blank=True, null=True)),
                (
                    "id_rol",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_rol",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="usuarios.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuario",
                "ordering": ["paterno", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="RolPermisoUsuario",
            fields=[
                (
                    "id_rol_permiso_usuario",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "id_rol_permiso",
                    models.ForeignKey(
                        db_column="id_rol_permiso",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="usuarios.rolpermiso",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rol_permisos",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol-Permiso de Usuario",
                "verbose_name_plural": "Roles-Permisos de Usuarios",
                "db_table": "rol_permiso_usuario",
                "unique_together": {("id_usuario", "id_rol_permiso")},
            },
        ),
    ]
