# Generated by Django 6.0.4 on 2026-04-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                ("id_proveedor", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=150, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
                ("nit", models.CharField(blank=True, max_length=20, null=True)),
                ("contacto", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": "proveedor",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Adquisicion",
            fields=[
                ("id_adquisicion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("estado", models.CharField(default="activo", max_length=20)),
                ("glosa", models.TextField(blank=True, null=True)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adquisiciones",
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adquisición",
                "verbose_name_plural": "Adquisiciones",
                "db_table": "adquisicion",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAdquisicion",
            fields=[
                ("id_detalle_adq", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_uni", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "id_adquisicion",
                    models.ForeignKey(
                        db_column="id_adquisicion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.adquisicion",
                    ),
                ),
                (
                    "id_almacen",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_almacen",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_adquisicion",
                        to="inventario.almacen",
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_adquisicion",
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Adquisición",
                "verbose_name_plural": "Detalles de Adquisición",
                "db_table": "detalle_adquisicion",
            },
        ),
        migrations.CreateModel(
            name="NotaCompra",
            fields=[
                ("id_compra", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_compra", models.DateField()),
                (
                    "total_compra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("nro_factura", models.CharField(blank=True, max_length=50, null=True)),
                ("estado", models.CharField(default="activo", max_length=20)),
                ("glosa", models.TextField(blank=True, null=True)),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("contado", "Contado"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                        ],
                        default="contado",
                        max_length=20,
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_compra",
                        to="usuarios.usuario",
                    ),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_proveedor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_compra",
                        to="compras.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Compra",
                "verbose_name_plural": "Notas de Compra",
                "db_table": "nota_compra",
                "ordering": ["-fecha_compra"],
            },
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                (
                    "id_detalle_compra",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_uni", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_compra",
                        to="inventario.producto",
                    ),
                ),
                (
                    "id_compra",
                    models.ForeignKey(
                        db_column="id_compra",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.notacompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Compra",
                "verbose_name_plural": "Detalles de Compra",
                "db_table": "detalle_compra",
            },
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                ("id_orden", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                ("estado", models.CharField(default="pendiente", max_length=20)),
                ("glosa", models.TextField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_compra",
                        to="usuarios.usuario",
                    ),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_proveedor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes",
                        to="compras.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "db_table": "orden_compra",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id_detalle_orden",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_uni", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sub_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_producto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detalles_orden",
                        to="inventario.producto",
                    ),
                ),
                (
                    "id_orden",
                    models.ForeignKey(
                        db_column="id_orden",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.ordencompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden de Compra",
                "verbose_name_plural": "Detalles de Orden de Compra",
                "db_table": "detalle_orden_compra",
            },
        ),
        migrations.AddField(
            model_name="adquisicion",
            name="id_orden",
            field=models.ForeignKey(
                blank=True,
                db_column="id_orden",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adquisiciones",
                to="compras.ordencompra",
            ),
        ),
        migrations.AddField(
            model_name="adquisicion",
            name="id_proveedor",
            field=models.ForeignKey(
                blank=True,
                db_column="id_proveedor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adquisiciones",
                to="compras.proveedor",
            ),
        ),
    ]
