# Generated by Django 6.0.4 on 2026-04-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
        ("inventario", "0002_alter_producto_options_alter_productoalmacen_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoProveedor",
            fields=[
                ("id_catalogo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "stock_disponible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("estado", models.CharField(default="activo", max_length=20)),
                (
                    "id_producto",
                    models.ForeignKey(
                        db_column="id_producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogos",
                        to="inventario.producto",
                    ),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        db_column="id_proveedor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogo",
                        to="compras.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catálogo de Proveedor",
                "verbose_name_plural": "Catálogos de Proveedores",
                "db_table": "catalogo_proveedor",
                "unique_together": {("id_proveedor", "id_producto")},
            },
        ),
    ]
